/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class HelloNative */

#ifndef _Included_HelloNative
#define _Included_HelloNative
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     HelloNative
 * Method:    getInt
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_HelloNative_getInt
  (JNIEnv *, jclass, jint);

/*
 * Class:     HelloNative
 * Method:    getString
 * Signature: (ILjava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_HelloNative_getString
  (JNIEnv *, jclass, jint, jstring);

/*
 * Class:     HelloNative
 * Method:    getSumOfArray
 * Signature: ([I)I
 */
JNIEXPORT jint JNICALL Java_HelloNative_getSumOfArray
  (JNIEnv *, jclass, jintArray);

/*
 * Class:     HelloNative
 * Method:    getArray
 * Signature: ([I)[I
 */
JNIEXPORT jintArray JNICALL Java_HelloNative_getArray
  (JNIEnv *, jclass, jintArray);

#ifdef __cplusplus
}
#endif
#endif
