/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class Dynamic */

#ifndef _Included_Dynamic
#define _Included_Dynamic
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     Dynamic
 * Method:    chello
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_Dynamic_chello
  (JNIEnv *, jclass, jint);

#ifdef __cplusplus
}
#endif
#endif
