/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class Jnidemo */

#ifndef _Included_Jnidemo
#define _Included_Jnidemo
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     Jnidemo
 * Method:    chello
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_Jnidemo_chello
  (JNIEnv *, jclass, jint);

#ifdef __cplusplus
}
#endif
#endif
