/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class HelloNative */

#ifndef _Included_HelloNative
#define _Included_HelloNative
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     HelloNative
 * Method:    chello
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_HelloNative_chello
  (JNIEnv *, jclass, jint);

#ifdef __cplusplus
}
#endif
#endif
